### ISSUE TITLE
Developer APIs

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-admin-dashboard#10]
@lalc  We don't have the wireframe for this page at the moment. But I am attaching a reference wireframe from iGrant.io ED here.
![2023-09-04_16-14](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/15c491db-20e8-414a-8bff-319eecaafef6)

**Comment by lalc** [comment]
![image](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/86b2274d-f8f0-4981-a43b-2edbadb89699)
