### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-admin-dashboard#12]
@lalc We don't have the wireframe for this page at the moment. But I am attaching a reference wireframe from iGrant.io ED here.
![2023-09-04_16-19](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/a893a78a-6716-43cd-a9f8-e5a5e63a4059)

**Comment by lalc** [comment]
![image](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/408cc8d3-eb72-404d-8137-7d2a7bcf8af2)
