### ISSUE TITLE
Styling issues: shall follow similar features as ED

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#143]
- [x] Hover over shall darken the button
- [x] All buttons shall be derived from a single format, so if one is changed, it is automatically changed everywhere
- [x] The panel colour shall be white
- [x] When a field is not editable, it shall have a grey background (See ED)
- [ ] Remove the spring effect in the menu bar when you pull it down. 
- [ ] Remove the spring effect in the main window when you pull down
- [ ] When you scroll page details, it shall NOT scroll the sidebar
- [x] The cover image height when you show shall be half of what is there. 
- [x] In the "Getting Started" screen, the organisation name and other details have disappeared when you click edit. 
- [x] Turn off autocomplete in the manage admin page for name
- [x] Draft data agreements should be highlighted in red colour.
- [x] In Manage users --> Configuration, when you click the + button, the dialogue pop-up is positioned at the bottom. It shall be positioned at the top as any dialog that pops up. 
- [ ] Check all edit functions. When you click edit, the whole field, textbox, line, etc, SHALL NOT move around. Please follow how Github or similar works when you try to edit.

**Comment by georgepadayatti** [comment]
@MARZOOQUE The panel background color should be white and not grey. Please check iGrant.io ED for reference.

<img width="470" alt="Screenshot 2023-10-31 at 10 17 19 AM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/cf0a1008-599e-4d82-acf9-4a4fc48ce066">
