### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-admin-dashboard#148]
- [x] Table content should be body2
- [x] Filter should be body2
- [x] Privacy dashboard detail should be body2
- [x] Entire page detail should be using body2 (User Access, Consent Records, Privacy Dashboard e.t.c.)

<img width="1173" alt="Screenshot 2023-10-31 at 10 08 05 AM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/64eef832-09cb-4980-8366-391aa8fbd5e7">

<img width="223" alt="Screenshot 2023-10-31 at 10 09 42 AM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/0747f654-f179-479d-a9b0-970c2fc774c0">

<img width="275" alt="Screenshot 2023-10-31 at 10 10 52 AM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/07e3fbfe-7a27-4d26-b1b6-209c55000609">

**Comment by MARZOOQUE** [comment]
@georgepadayatti  Table Contents are already body2, is it table header to be in body2??

**Comment by georgepadayatti** [comment]
> @georgepadayatti Table Contents are already body2, is it table header to be in body2??

Yes
