### ISSUE TITLE
Unable to open user record modal for view data agreement

### ISSUE THREAD

**Issue by MARZOOQUE** [decentralised-dataexchange/bb-consent-admin-dashboard#165]

**Comment by sreelakshmyunnikrishnan** [comment]
@MARZOOQUE able to open but has empty fields 
![Screenshot 2023-11-02 at 18-42-08 Admin Dashboard](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/44528546/3da5cc93-0c1f-475e-bab3-c36163bb6dd1)
