### ISSUE TITLE
Issue - Data Agreements 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-admin-dashboard#178]
- [x] choose existing schema to be removed
- [x] After editing - the data source is changed
- [ ]  if we edit a published data agreement and save it, it goes to draft. It should the current published one 
- [x]  Ater changing the retention period and save the data agreement. Then viewd it, the retention period is wrong
- [x]  Updated the consent to contract, then we save it, after that viewed it, then published it -> contract changed to consent
- [x] On editing we add new attribute, then save it. On View it dissapears. 
- [x]  Edited the data agreement to legal obligation -> saved -> published -> it changed to contract
- [x] create a data agreement -> add details -> save it -> edit the data agreement -> delete all the data attributes -> save it -> Publish from data agreement listing -> it is now showing the deleted attributes

- [x] On clicking Published, it doesn't show Published DA

**Comment by MARZOOQUE** [comment]
@georgepadayatti @kashishmalik  As we discussed yesterday The 3rd issue will be drafted right? So can we remove that from the issue list?
"if we edit a published data agreement and save it, it goes to draft. It should the current published one"

**Comment by lalc** [comment]
@georgepadayatti Please review the scenario of handling draft and published revisions:

Scenario: A DA existing with version, say, 1.0

1) The admin chooses edit, begins to modify, and clicks save. 

In this case, there shall be two DAs—one as draft (2.0). The DA list shall show one draft and one published for the same DA. 

2) The admin now chooses to edit the draft and publish it. 

Two DA revisions will be published in this case, but the latest is available to the user. The DA list shall show the latest published one. 

Two additional possibilities: 
#01: If the admin chooses to edit the original published one. 
#02:Edit shall be available only for the latest published revision

**Comment by georgepadayatti** [comment]
Need clarification. This flow is confusing. Will require  some serious
changes in the architecture as well.

**Comment by lalc** [comment]
How do you suggest in the short run? @georgepadayatti

**Comment by georgepadayatti** [comment]
> How do you suggest in the short run? @georgepadayatti

@lalc I am sharing the different cases for data agreement create/update (do parse through them in sequential order)

<img width="825" alt="Screenshot 2023-11-04 at 10 54 27 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/96b864a2-b3c4-4c24-b5a6-7b88efe25511">

<img width="866" alt="Screenshot 2023-11-04 at 10 54 45 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/bd8eeb8c-3c19-43c0-a6a4-023214410cbd">

<img width="818" alt="Screenshot 2023-11-04 at 10 54 33 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/773a269e-e648-4597-b9be-dcd3099afdc5">

<img width="764" alt="Screenshot 2023-11-04 at 10 54 51 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/d1eb628d-bdb5-4aa4-8279-6e5daeab1c5b">


Assuming you are in consensus to all these cases. The only change required is ability to see past revision from drop down. Past revisions can only be viewed and cannot be edited. If you delete a data agreement, you are deleting all the revisions.

<img width="1171" alt="Screenshot 2023-11-04 at 10 56 40 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/8964f9cd-89a0-4953-98aa-f235ddcf9b5d">

**Comment by lalc** [comment]
Let's stick to this for now.

Question: Could we not have revision as x.y?

**Comment by georgepadayatti** [comment]
> Let's stick to this for now.

You are in consensus correct ?

> Question: Could we not have revision as x.y?
Meaning ?

**Comment by georgepadayatti** [comment]
> Let's stick to this for now.

You are in consensus correct ?

> Question: Could we not have revision as x.y?
Meaning ?

**Comment by georgepadayatti** [comment]
> Let's stick to this for now.
> I am unsure about the delete, but I can live with it for now. Pls state it in the deletion warning for now.

Can you suggest a text ? I can raise it as a separate issue to avoid missing it.

**Comment by georgepadayatti** [comment]
> > Let's stick to this for now.
> > I am unsure about the delete, but I can live with it for now. Pls state it in the deletion warning for now.
> 
> Can you suggest a text ? I can raise it as a separate issue to avoid missing it.

<img width="465" alt="Screenshot 2023-11-04 at 11 16 47 PM" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/fbe23674-e489-4d61-94f6-732906b1547a">

@lalc ☝🏼 This is the current text.

**Comment by lalc** [comment]
You are about to delete an existing data agreement and ALL its revisions. This action is not reversible. Please type DELETE to confirm and click DELETE.

**Comment by georgepadayatti** [comment]
@MARZOOQUE 

> Here is the revised warning text:
> 
> You are about to delete an existing data agreement and ALL its revisions. This action is not reversible. Please type DELETE to confirm and click DELETE.

**Comment by georgepadayatti** [comment]
@MARZOOQUE Drop down for version of data agreement should as shown below:

![2023-11-06_16-52](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/c07143d3-07d6-429b-9c19-58f946de7081)
