### ISSUE TITLE
Creating a new DA shows version number as 0.0.0

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#185]
@georgepadayatti Can you please check if we need the version number field when we create a new DA? 

@MARZOOQUE 
It's misleading as it comes up as 0.0.0 with a mandatory * mark. Why is this so? 

Please use this thread to discuss and agree on how we handle this. 

Note: This is applicable only when you create a new DA. For updating, viewing, and deleting, it shall show the version. 

- [ ] Handle the above issue
- [ ] Once the draft is saved. the revision shall NOT be 0.0.0 as is below:

<img width="1261" alt="Screenshot 2023-11-04 at 17 23 08" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/33fa4add-7ad5-493a-85da-57e3ac340e91">

**Comment by georgepadayatti** [comment]
> @georgepadayatti Can you please check if we need the version number field when we create a new DA?

This field is removed in 'CREATE' panel ?

![2023-11-06_17-58](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/00c63495-d203-4231-bc73-72d04b5126ae)

**Comment by georgepadayatti** [comment]
> > @georgepadayatti Can you please check if we need the version number field when we create a new DA?
> 
> This field is removed in 'CREATE' panel ?
> 
> ![2023-11-06_17-58](https://user-images.githubusercontent.com/16397960/280705849-00c63495-d203-4231-bc73-72d04b5126ae.png)

@MARZOOQUE You don't have to remove the version.
