### ISSUE TITLE
The column text moves when the DA is edited and a draft is created

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#186]
Please take a look at the attached video.

https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/eede4259-1668-4e3f-b76a-818ac560f879

**Comment by MARZOOQUE** [comment]
@lalc  In enterprise dashboard also we have same behaviour, its happening because the text size is changing

[Screencast from 06-11-23 07:43:39 PM IST.webm](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/61059336/d56d4911-8065-4985-a9f0-f653d5a35408)

**Comment by lalc** [comment]
Thanks for explaining. Question: Which text size is changing in the example I shared?

**Comment by MARZOOQUE** [comment]
> Thanks for explaining. Question: Which text size is changing in the example I shared?

When you update published data agreement to draft the status text in the table will change
