### ISSUE TITLE
Clicking developer doc is taking to iGrant.io dev docs

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#188]
In this case, a default developer doc shall be created. 

@georgepadayatti Could it be a GitHub page or a published version of the developer doc pdf, to begin with? (We of course, do not want to make it complicated with docusaurus for this for now; keep it simple)

**Comment by georgepadayatti** [comment]
Link to pdf makes sense.

**Comment by lalc** [comment]
Or I can convert it to a .me file that can he linked.

**Comment by georgepadayatti** [comment]
> Or I can convert it to a .me file that can he linked. 

Yes. A link towards bb-consent-docs wiki.

**Comment by kashishmalik** [comment]
https://github.com/decentralised-dataexchange/bb-consent-docs/wiki/developer-documentation
