### ISSUE TITLE
End-user image update doesnt give any feedback

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#211]
1. Clicked edit
2. Uploaded the image
3. Clicked SAVE
4. Nothing happens
5. When the screen is refreshed, it updates the image on the top right corner and the box. This happens even if you cancel after clicking save. 

https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/0daad9de-7536-425e-ba4a-59135604dceb

**Comment by kashishmalik** [comment]
@MARZOOQUE Can you please check this again? I am facing this issue. At times one image changes and another doesn't.

**Comment by lalc** [comment]
Could we please agree not to close issues arbitrarily? I haven't tested this .. and when I checked today with the latest version, it still isn't done. It doesn't work.
