### ISSUE TITLE
Admin Logs filter: It shall be possible to filter using multiple choices as in ED

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#212]
Please see the behaviour in iGrant.io SD for filtering logs.

**Comment by sreelakshmyunnikrishnan** [comment]
![Screenshot from 2024-01-04 13-09-33](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/44528546/95f5c6a6-2670-43fd-b0cf-9c6800d56218)

**Comment by georgepadayatti** [comment]
@MARZOOQUE Can you add the pending action point here ? Would like to understand, how is this progressing.

**Comment by MARZOOQUE** [comment]
> @MARZOOQUE Can you add the pending action point here ? Would like to understand, how is this progressing.

@georgepadayatti Its completed from my end. i was waiting for @kashishmalik to complete the testing and close the issue

**Comment by georgepadayatti** [comment]
> > @MARZOOQUE Can you add the pending action point here ? Would like to understand, how is this progressing.
> 
> @georgepadayatti Its completed from my end. i was waiting for @kashishmalik to complete the testing and close the issue

Can you share a screenshot of the final changes ?
