### ISSUE TITLE
In Consent records - View Data agreement shows data retention period in days instead of years

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-admin-dashboard#238]
In Consent records - View Data agreement shows data retention period in days instead of years

![Screenshot 2023-11-10 at 22-13-25 Admin Dashboard](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/92527972/c7caf889-0209-4954-920f-c98fe7832a20)

**Comment by MARZOOQUE** [comment]
https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/pull/239

FIx is pushed in this pr
