### ISSUE TITLE
Avtar image update doesnt work properly

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#243]
I updated the avatar image, and it doesn't work correctly. A few issues noticed are:

- [x] The name field is removing the existing name when you click edit (0:01)
- [x] When you clicked save, it doesn't update the same image at the top right corner. It still shows the old image. 
- [x] Immediately after saving, the old image seems to be loading briefly before changing to the new image.

See video.

https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/3830cabc-8e76-4ed2-b8d5-20837192c707

**Comment by MARZOOQUE** [comment]
[Screencast from 14-11-23 08:43:18 AM IST.webm](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/61059336/7ddb71bb-2d8c-49ce-b06f-cb5a9563b015)



@lalc the 3rd scenario will be there as it takes a small time delay for the new api response. 
i have added reference screenshot from our enterprise dashboard

**Comment by lalc** [comment]
Third scenario: why doesn't it happen with cover image or cover logo?

**Comment by MARZOOQUE** [comment]
Both scenarios are different. in getting started page it directly uploads the image but in manage admin it uploads on clicking save

Both in admin and enterprise dashboard scenario are same

**Comment by lalc** [comment]
> Both scenarios are different. in getting started page it directly uploads the image but in manage admin it uploads on clicking save
> 
> Both in admin and enterprise dashboard scenario are same

Why should the behavior be different?

**Comment by lalc** [comment]
Also, how can you save it before you click save?

**Comment by lalc** [comment]
All working now.
