### ISSUE TITLE
When editing personal data, the data agreement new revisions are created and published automatically

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#248]
Now, if I go to Personal Data and modify one of the attributes, it automatically publishes the new DA for every DA that uses that attribute. 

In this case, I would like the DA to be in a draft state. Or may be disable edit option completely at personal data level as we dont have them normalised anyways.

**Comment by kashishmalik** [comment]
The decision is to not show EDIT coloumn in Personal data.
