### ISSUE TITLE
Edit of org, the edit line is touching the org name

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#268]
See the screenshot:

<img width="1494" alt="Screenshot 2023-11-15 at 12 54 39" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/99871475-d1ce-45c8-8764-432de83b4444">

**Comment by MARZOOQUE** [comment]
- [ ] Reduce the space between overview and its above details
- [ ] Reduce the height of 4 links which contains the links
