### ISSUE TITLE
Login as organisation admin

### ISSUE THREAD

**Issue by lalc** [decentralised-dataexchange/bb-consent-admin-dashboard#3]
- [ ] Use Govstack logos on the login page; the wireframe for the login screen is below:

![image](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/3c15a4f6-1bfd-4527-9ba6-21f091f603fa)

- [ ] The following screen is shown to the admin users after successful login:

<img width="991" alt="Screenshot 2023-08-24 at 15 26 45" src="https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/455274/3cb238ab-1363-4a5e-858c-8df8780c5375">

**NOTE:** There is no need to have the ability to self-registration, etc., and a mere login screen is enough.

**Comment by georgepadayatti** [comment]
@MARZOOQUE Small change in the above wireframes: 

1. Consent Agreements should be replaced with Data Agreements
2. Under Manage User Records, Consent Records should be replaced with DA Records

**Comment by georgepadayatti** [comment]
_Question from Marzooque (in slack channel): what should be the behaviour of user icon in the AppBar while clicking on it._

We shall retain the behaviour we have in Enterprise Dashboard. On click, a drop down is shown with relevant menu items.

![File (8)](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/66947307-7a9c-4cfd-ab36-84ef545e6b80)

**Comment by lalc** [comment]
Yes, please reuse the same as what we have for privacy dashboard.

**Comment by MARZOOQUE** [comment]
@lalc @georgepadayatti  for breadcrumbs we have to use same behaviour as in enterprise dashboard right?

**Comment by georgepadayatti** [comment]
> @lalc @georgepadayatti for breadcrumbs we have to use same behaviour as in enterprise dashboard right?

Yes.

**Comment by lalc** [comment]
Yes Sent from my iPhoneOn 6 Sep 2023, at 08:27, George J Padayatti ***@***.***> wrote:﻿

@lalc @georgepadayatti for breadcrumbs we have to use same behaviour as in enterprise dashboard right?

Yes.
