### ISSUE TITLE
The previous values of Data Sources Configuration get erased if we add an empty Data Source Configuration

### ISSUE THREAD

**Issue by sreelakshmyunnikrishnan** [decentralised-dataexchange/bb-consent-admin-dashboard#319]
Steps to reproduce:

1. Create a DA (DUS) with Data Source configuration ( add two or more)
2. Edit the DA to add an empty Data Source configuration
3. Publish or SAVE the DA
4. Again try to edit the DA, and if we view the configuration we can see that all the previous values are erased.
Note: This scenario also happens when we try to create DA with one Data source configuration filled and other as empty

![Screenshot from 2024-10-03 18-29-33](https://github.com/user-attachments/assets/9f2f9438-c35f-42ef-837a-f0d98b9fb011)

**Comment by MARZOOQUE** [comment]
Fixed: https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/pull/321
