### ISSUE TITLE
Correction in Getting started page 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-admin-dashboard#32]
1. Sector, Location, Policy URL - to be black color
2. Font size for Oranganisation name to be reduced
3. Overview to be one line up 
4. One line gap between Overview and Description
5. Boxex to be smaller in size and shift up to be inside page like wireframe. 
6. Home / Getting started - The gap between should be reduced

**Comment by lalc** [comment]
Think we can't afford to write issues for such things. 

Is there any UI design guideline we could adopt and follow? 

Most issues like spacing, uniform fonting, look-n-feel should be taken care during design itself.

@MARZOOQUE If you wish take a screeenshot before you commit code and get early comments via slack. Let's not consume too much time from testing for these. Of course, there could be exceptions.
