### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-admin-dashboard#7]
@lalc We don't have the wireframe for this page at the moment. But I am attaching a reference wireframe from iGrant.io ED here.

![2023-09-04_16-02](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/a1170030-7168-463b-80d6-7610825d97b7)

**Comment by lalc** [comment]
Need to discuss this before finalising the screen
