### ISSUE TITLE
Privacy board

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-admin-dashboard#8]
@lalc We don't have the wireframe for this page at the moment. But I am attaching a reference wireframe from iGrant.io ED here.

![2023-09-04_16-10](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/16397960/4102d138-63c9-4b4a-96f0-bc63affe810e)

**Comment by MARZOOQUE** [comment]
![PrivacyBoard](https://github.com/decentralised-dataexchange/bb-consent-admin-dashboard/assets/61059336/2704cb44-a50f-4a8a-8e79-9741ad0e1412)


@lalc @georgepadayatti  In the reference image its mentioned configure button is not required, but in the latest design the configure button is not removed yet. is that added by mistake or do need to add configure button

**Comment by MARZOOQUE** [comment]
@lalc In the latest design breadcrumb text is Home/ Manage Consent/ Privacy Board instead Home / PrivacyBoard. 
I am adding actual path for breadcrumb instead the mistaken path.

**Comment by lalc** [comment]
Thank you for pointing this out.

Could we please stick to the slide I shared for all UI designs? You can comment on the slide itself and as can get it fixed. Ok?
