### ISSUE TITLE
Correction in Data Agreement page

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-admin-dashboard#99]
1. On creating DA, it shows the disable button to Save or Publish. 
2. In the Published agreement list, it shows Draft ones as well 
3. Once the agreement is created and clicked on Publish, it doesn't immediately show in the dashboard. Need to fresh or login again to be shown. 
4. On editing existing DA, when updating attributes, it shows a disable button n doesn't let to Save or Publish

**Comment by MARZOOQUE** [comment]
Please retest
